"""
tools/email_formatter.py
------------------------
Responsible for assembling the final email string from the LLM's raw output.

WHY A SEPARATE FORMATTER?
--------------------------
The Groq model returns a raw text block. This module wraps it in consistent
email metadata (To, From, Date, Subject) so the output file looks like a
real email draft rather than a naked text blob.

Separation of concerns:
- groq_client.py  → API communication
- email_formatter.py → presentation / structure
- main.py         → orchestration

This also makes it easy to swap the output format later (e.g., HTML email,
JSON payload for an SMTP library) without touching the LLM code.
"""

from datetime import datetime

from utils.logger import get_logger

logger = get_logger(__name__)


def format_email(
    topic: str,
    llm_output: str,
    recipient: str = "research-team@example.com",
    sender: str = "research-agent@example.com",
) -> str:
    """
    Wrap the LLM's email body in standard email headers.

    Args:
        topic:      The original research topic (used for the Subject line).
        llm_output: The raw email body generated by the LLM.
        recipient:  To: address (placeholder for a real integration).
        sender:     From: address.

    Returns:
        A fully formatted email string ready to be saved or sent.
    """
    logger.info("Formatting final email for topic: '%s'", topic)

    timestamp = datetime.now().strftime("%A, %d %B %Y at %H:%M")

    # Build the email header block.
    # In a real project you'd use Python's `email` stdlib or pass this to
    # an SMTP client (smtplib). For now, plain text is sufficient.
    header = (
        f"To: {recipient}\n"
        f"From: {sender}\n"
        f"Date: {timestamp}\n"
        f"Subject: Research Summary - {topic}\n"
        f"{'-' * 60}\n\n"
    )

    footer = (
        f"\n\n{'-' * 60}\n"
        f"This email was generated automatically by the Research Email Agent.\n"
        f"Generated at: {timestamp}\n"
    )

    formatted = header + llm_output.strip() + footer

    logger.debug(
        "Email formatted successfully (%d chars total).", len(formatted)
    )
    return formatted


def validate_email_output(email_text: str) -> bool:
    """
    Basic sanity check on the formatted email before saving.

    In production you might check for:
    - Minimum content length (guard against empty LLM responses).
    - Presence of expected sections (Introduction, Key Findings, etc.).
    - No placeholder text like "[INSERT NAME HERE]" still in the output.

    Args:
        email_text: The formatted email string.

    Returns:
        True if the email passes basic checks, False otherwise.
    """
    if not email_text or len(email_text.strip()) < 100:
        logger.error(
            "Email validation failed: content is too short (%d chars).",
            len(email_text),
        )
        return False

    # Check that the LLM actually produced a body and didn't just echo the prompt.
    if "{{" in email_text or "}}" in email_text:
        logger.error(
            "Email validation failed: output contains unfilled template placeholders."
        )
        return False

    logger.debug("Email validation passed.")
    return True
